# Docs and examples to use:
# https://docs.travis-ci.com/user/languages/android
# http://panavtec.me/continous-integration-on-android-with-travis-ci
# https://github.com/codecov/example-android/blob/master/.travis.yml
# https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI
# http://stackoverflow.com/questions/34621124/using-travis-ci-with-android
language: android
jdk: oraclejdk8
env:
  global:
    # Looks like android-24 doesn't work yet...
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  # http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
  - chmod +x gradlew
before_script:
  - uname -a
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
script:
  - ./gradlew build assembleAndroidTest
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  # Instead of this (which doesn't give any output during tests execution):
  # - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace
  # run:
  - adb shell am instrument -w -e func true org.andstatus.app.tests/android.test.InstrumentationTestRunner
  # See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
after_success:
  # TODO: SonarQube