# Docs and examples to use:
# https://docs.travis-ci.com/user/languages/android
# http://panavtec.me/continous-integration-on-android-with-travis-ci
# https://github.com/codecov/example-android/blob/master/.travis.yml
# https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI
# http://stackoverflow.com/questions/34621124/using-travis-ci-with-android
# https://github.com/travis-ci/travis-ci/issues/6122 Android - Missing emulator ABI due to bad SDK Tools version
language: android
jdk: oraclejdk8

sudo: required

env:
  global:
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_API_LEVEL

before_install:
  # http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
  - chmod +x gradlew

before_script:
  - uname -a
  - android list targets
  - ls -la $HOME/.android/**/*
  - ls -la $HOME/**/*
  # Create and start emulator
  - echo no | android create avd --force -n test -t "android-"$ANDROID_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - ls -la $HOME/.android/**/*
  - ls -la $HOME/**/*
  - cat $HOME/.android/avd/test.avd/config.ini
  - cp res-src/avd_config.ini $HOME/.android/avd/test.avd/config.ini
  - cat $HOME/.android/avd/test.avd/config.ini
  - emulator -avd test -no-window &
  - travis_wait 30 android-wait-for-emulator
  # Previous command seems to end too early, so wait a bit more
  # On multilined commands: https://gitlab.com/gitlab-org/gitlab-ci/issues/258 and http://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines
  - |
    while ! adb shell getprop init.svc.bootanim; do
      echo Waiting for boot animation to end
      sleep 10
    done
  # Another method. Should print SDK version number to console
  # See http://stackoverflow.com/questions/28195080/unknown-api-level-error-when-trying-to-run-instrumentation-test
  - |
    while ! adb shell getprop ro.build.version.sdk; do
      echo Waiting for ro.build.version.sdk value from device
      sleep 10
    done
  - adb devices
  - adb shell input keyevent 82 &

script:
  - |
    ./gradlew build assembleAndroidTest
    retval=$?
    if [ $retval -ne 0 ]; then
      echo "error on assembling, exit code: "$retval
      exit $retval
    fi

  # See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
  # Instead of this (which doesn't give any output during tests execution):
  # - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
  # run:
  - |
    ./gradlew :app:installDebugAndroidTest :app:installDebug
    retval=$?
    if [ $retval -ne 0 ]; then
      echo "error on install, exit code: "$retval
      exit $retval
    fi

  #
  # The below line causes Process crash due to absense of video device
  #- adb shell am instrument -w -r -e debug false org.andstatus.app.tests/android.test.InstrumentationTestRunner
  #
  # Run only tests, marked with a special annotation:
  # See https://developer.android.com/reference/android/test/InstrumentationTestRunner.html
  # For testing one method only:
  # - adb shell am instrument -w -r -e debug false -e class org.andstatus.app.msg.ActAsUserTest#testActAsUser org.andstatus.app.tests/android.test.InstrumentationTestRunner
  - |
    adb shell am instrument -w -r -e annotation org.andstatus.app.context.Travis org.andstatus.app.tests/android.test.InstrumentationTestRunner |& tee build/adb-test.log
    retval=$?
    if [ $retval -ne 0 ]; then
      echo "error in adb, exit code: "$retval
      exit $retval
    fi

  # adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
  # So we need to parse saved terminal log
  - |
    cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack="
    if [ $? -eq 0 ]; then
      echo "Test failure found"
      exit 1
    else
      cat build/adb-test.log | grep "Test results for InstrumentationTestRunner"
    fi

# See https://docs.travis-ci.com/user/languages/java/#Projects-Using-Gradle
before_cache:
  - ls -la $HOME/.gradle/**/*
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true
